version: "3.3"

services:
  php73_laravel:
    container_name: php73_laravel
    build: ../php73_laravel/
    restart: unless-stopped
    volumes:
      - "${STORAGE_PATH}:/var/project"
      - "${CRON_PATH}:/etc/cron.d/schedule-cron"
    command: >
      bash -c "cd resources/nuxt
      && pm2 start -i 2 npm --name 'nuxt' -- run start
      && chmod 0777 /etc/cron.d/schedule-cron
      && crontab /etc/cron.d/schedule-cron
      && service cron restart
      && php-fpm"
    ports:
      - 80:3000
    depends_on:
      - mysql57
    networks:
      - dev

  mysql57:
    container_name: mysql57
    image: mysql:5.7
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - mysql57-data:/var/lib/mysql
    networks:
      - dev

  nginx:
    container_name: nginx
    build: ../nginx
    restart: unless-stopped
    ports:
      - 8081:80
    volumes:
      - "${STORAGE_PATH}:/var/project"
      - "${LOG_PATH}:/var/log/nginx"
      - ../nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - dev

networks:
  dev:

volumes:
  mysql57-data:
